#ifndef PANTALLA_H
#define PANTALLA_H

enum class PANTALLA { MENU_PRINCIPAL, COLOR_DEL_TEXTO = 2, COLOR_DEL_FONDO, CAMBIAR_TITULO, REACCION_DE_TECLAS, CONFIRMACION_DE_SALIDA };

#endif // !PANTALLA_H
